### ISSUE TITLE
Why the loop in the example? Is 500 iteration always enough?

### ISSUE THREAD

**Issue by thmxv** [MIERUNE/earcut-rs#15]
The example contains the following:
```rust
for _ in 0..500 {
    earcut.earcut(vertices.iter().copied(), &hole_indices, &mut triangles);
}
```
I did not found (in the doc) any information on why the 500 iterations? Is this really needed? Is 500 always enough to have a fully triangulated result? Or, to know when to stop, is it better to check that the triangle count stopped getting higher?

**Comment by ciscorn** [comment]
@thmxv Thank you.
The loop was mistakenly copied from benchmarking code and is entirely unnecessary. You only need to call earcut once for it to work correctly.
