### ISSUE TITLE
Use const generics

### ISSUE THREAD

**Issue by Shatur** [MIERUNE/earcut-rs#3]
I would like to suggest to pass a slice of arrays with dimension defined as const generic. And instead of accepting dimensions as a number, use `[usize; 2]` with indices to use. I.e. to use first two values from each array (x and y), use `[0, 1]`.
It would be more ergonomic and more efficient since libraries usually represent meshes as vector of arrays instead of vector of values.

**Comment by ciscorn** [comment]
Thanks for your comment.

That is more ergonomic (constant generics are good), but there are some concerns:

- It deviates from the original JavaScript API, and we must overhaul the internal code.
- With data like "slices of values," there is some cost to repack vertices into slices of value arrays.

That said, there is a possibility of changing the API.

**Comment by ciscorn** [comment]
@Shatur Thanks for your comment.

That is more ergonomic (and constant generics are nice), but there are some concerns:

- It deviates from the original JavaScript API, and we must overhaul the internal code.
- With data like "slices of values," there is some cost to repack vertices into slices of value arrays.

That said, there is a possibility of changing the API.

**Comment by ciscorn** [comment]
@Shatur Thanks for your comment.

That is more ergonomic (and const generics are nice), but there are some concerns:

- It deviates from the original JavaScript API, and we must overhaul the internal code.
- With data like "slices of values," there is some cost to repack vertices into slices of value arrays.

That said, there is a possibility of changing the API.

**Comment by Shatur** [comment]
> It deviates from the original JavaScript API, and we must overhaul the internal code.

Understandable, but maybe it's not that bad since the original library changed two years ago?

> With data like "slices of values," there is some cost to repack vertices into slices of value arrays.

Are there any librararies which represent data as slice of values? All libraries I know represent data as vectors of array ([here](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html) is Bevy, for example, see how `ATTRIBUTE_POSITION` is initialized). So it's vice versa - there is a cost to convert data into slice of values (at least in my case).

**Comment by ciscorn** [comment]
I'm working on the [v0.2](https://github.com/MIERUNE/earcut-rs/tree/v0.2) branch to change the API to use `impl IntoIterator<Item=&'a [T; 2]>`.

**Comment by Shatur** [comment]
It would be awesome, thanks!
