### ISSUE TITLE
More API suggestions

### ISSUE THREAD

**Issue by Shatur** [MIERUNE/earcut-rs#6]
Hi! Thanks a lot for implementing my suggestions in #5. I decided to try the crate, but noticed a few inconveniences with the API:

1. You now accept iterator for vertices which is quite convenient, but you require item to be `&[f32; 2]`. It's a problem when you actually have 3D coordinates and you trying to convert them into 2D:
```rust
positions.iter().map(|&[x, y, _]| &[x, y]);
```
I can't return `&[x, y]` from a closure. I would suggest to remove the reference (make it just `[f32; 2]`) or make turn it into an iterator over just `f32`. I would suggest the latter since it will be a little closer to how the JS version works.

2. You return triangles as `Vec<[N; 3]>`. But some crates, like Bevy, store them as just `f32`. I would suggest to return just `Vec<N>`. This way it will be more consistent with (1).

**Comment by ciscorn** [comment]
> I would suggest to return just Vec<N>

I agree that flat vectors are more useful.

> I can't return &[x, y] from a closure.

Oh, I only tested it on arrays and it worked fine. But it definitely doesn't work on iterators. Thanks!

```rust
    // with 3-d vertex array
    let mut earcut = Earcut::new();
    let data = [
        [0.0, 0.0, 1.0], [100.0, 0.0, 1.0], [100.0, 100.0, 1.0], [0.0, 100.0, 1.0],
    ];
    let hole_indices: &[usize] = &[];
    let mut triangles = vec![];
    earcut.earcut(&data.map(|v| [v[0], v[1]]), hole_indices, &mut triangles);
```

I'll change the both.

**Comment by ciscorn** [comment]
> or make turn it into an iterator over just f32. I would suggest the latter

looks nice 👌

**Comment by Shatur** [comment]
@ciscorn thank you a lot! I successfully migrated from `earcutr` to your crate. I like yours more because I can re-use the memory. I use it to triangulate walls in my game (doors or windows cut holes):
![Screenshot_%Y%M%D_%H%m%S-15](https://github.com/MIERUNE/earcut-rs/assets/22453358/97e0c2be-4d5c-45f4-bcec-d89ec4be3d69)
![Screenshot_%Y%M%D_%H%m%S-16](https://github.com/MIERUNE/earcut-rs/assets/22453358/f7e13a7a-06fb-4752-bc4c-e613672860fb)

Could you also publish your crate on crates.io?

**Comment by ciscorn** [comment]
@Shatur Thanks for sharing a fantastic use case!

> I like yours more because I can re-use the memory.

Glad to hear. Avoiding allocations is one of the intended improvements.

> Could you also publish your crate on crates.io?

OK, we will publish it shortly.

**Comment by ciscorn** [comment]
@Shatur Published!
https://crates.io/crates/earcut-rs
